/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_lib_Cocos2dxWebViewHelper */

#ifndef _Included_org_cocos2dx_lib_Cocos2dxWebViewHelper
#define _Included_org_cocos2dx_lib_Cocos2dxWebViewHelper
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: handler */
/* Inaccessible static: cocos2dxActivity */
/* Inaccessible static: layout */
/* Inaccessible static: webViews */
/* Inaccessible static: viewTag */
/*
 * Class:     org_cocos2dx_lib_Cocos2dxWebViewHelper
 * Method:    shouldStartLoading
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cocos2dx_lib_Cocos2dxWebViewHelper_shouldStartLoading
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_cocos2dx_lib_Cocos2dxWebViewHelper
 * Method:    didFinishLoading
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxWebViewHelper_didFinishLoading
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_cocos2dx_lib_Cocos2dxWebViewHelper
 * Method:    didFailLoading
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxWebViewHelper_didFailLoading
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_cocos2dx_lib_Cocos2dxWebViewHelper
 * Method:    onJsCallback
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_lib_Cocos2dxWebViewHelper_onJsCallback
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
